export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST";
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS";
export const GET_ALL_COURSE_FAILURE = "GET_ALL_COURSE_FAILURE";

export const GET_COURSE_BY_ID_REQUEST = "GET_COURSE_BY_ID_REQUEST";
export const GET_COURSE_BY_ID_SUCCESS = "GET_COURSE_BY_ID_SUCCESS";
export const GET_COURSE_BY_ID_FAILURE = "GET_COURSE_BY_ID_FAILURE";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";

export const UPDATE_COURSE_BY_ID_REQUEST = "UPDATE_COURSE_BY_ID_REQUEST";
export const UPDATE_COURSE_BY_ID_SUCCESS = "UPDATE_COURSE_BY_ID_SUCCESS";
export const UPDATE_COURSE_BY_ID_FAILURE = "UPDATE_COURSE_BY_ID_FAILURE";

export const DALETE_COURSE_BY_ID_REQUEST = "DALETE_COURSE_BY_ID_REQUEST";
export const DALETE_COURSE_BY_ID_SUCCESS = "DALETE_COURSE_BY_ID_SUCCESS";
export const DALETE_COURSE_BY_ID_FAILURE = "DALETE_COURSE_BY_ID_FAILURE";


//COURSE REVIEW 
export const GET_ALL_COURSEREIVEW_REQUEST = "GET_ALL_COURSEREIVEW_REQUEST";
export const GET_ALL_COURSEREIVEW_SUCCESS = "GET_ALL_COURSEREIVEW_SUCCESS";
export const GET_ALL_COURSEREIVEW_FAILURE = "GET_ALL_COURSEREIVEW_FAILURE";

export const CREATE_COURSEREVIEW_REQUEST = "CREATE_COURSEREVIEW_REQUEST";
export const CREATE_COURSEREVIEW_SUCCESS = "CREATE_COURSEREVIEW_SUCCESS";
export const CREATE_COURSEREVIEW_FAILURE = "CREATE_COURSEREVIEW_FAILURE";

export const DELETE_COURSERV_BY_RVID_REQUEST = "DELETE_COURSERV_BY_RVID_REQUEST";
export const DELETE_COURSERV_BY_RVID_SUCCESS = "DELETE_COURSERV_BY_RVID_SUCCESS";
export const DELETE_COURSERV_BY_RVID_FAILURE = "DELETE_COURSERV_BY_RVID_FAILURE";

// COURSE APPROVED
export const CREATE_APPROVE_COURSE_REQUEST = "CREATE_APPROVE_COURSE_REQUEST";
export const CREATE_APPROVE_COURSE_SUCCESS = "CREATE_APPROVE_COURSE_SUCCESS";
export const CREATE_APPROVE_COURSE_FAILURE = "CREATE_APPROVE_COURSE_FAILURE";

//LIVE COURSE 
export const GET_ALL_LIVESTREAM_REQUEST = "GET_ALL_LIVESTREAM_REQUEST";
export const GET_ALL_LIVESTREAM_SUCCESS = "GET_ALL_LIVESTREAM_SUCCESS";
export const GET_ALL_LIVESTREAM_FAILURE = "GET_ALL_LIVESTREAM_FAILURE";

export const CREATE_LIVESTREAM_REQUEST = "CREATE_LIVESTREAM_REQUEST";
export const CREATE_LIVESTREAM_SUCCESS = "CREATE_LIVESTREAM_SUCCESS";
export const CREATE_LIVESTREAM_FAILURE = "CREATE_LIVESTREAM_FAILURE";

export const GET_LIVESTREAM_BY_LIVEID_REQUEST = "GET_LIVESTREAM_BY_LIVEID_REQUEST";
export const GET_LIVESTREAM_BY_LIVEID_SUCCESS = "GET_LIVESTREAM_BY_LIVEID_SUCCESS";
export const GET_LIVESTREAM_BY_LIVEID_FAILURE = "GET_LIVESTREAM_BY_LIVEID_FAILURE";

export const UPDATE_LIVESTREAM_BY_LIVEID_REQUEST = "UPDATE_LIVESTREAM_BY_LIVEID_REQUEST";
export const UPDATE_LIVESTREAM_BY_LIVEID_SUCCESS = "UPDATE_LIVESTREAM_BY_LIVEID_SUCCESS";
export const UPDATE_LIVESTREAM_BY_LIVEID_FAILURE = "UPDATE_LIVESTREAM_BY_LIVEID_FAILURE";

export const DELETE_LIVESTREAM_BY_LIVEID_REQUEST = "DELETE_LIVESTREAM_BY_LIVEID_REQUEST";
export const DELETE_LIVESTREAM_BY_LIVEID_SUCCESS = "DELETE_LIVESTREAM_BY_LIVEID_SUCCESS";
export const DELETE_LIVESTREAM_BY_LIVEID_FAILURE = "DELETE_LIVESTREAM_BY_LIVEID_FAILURE";

//MODULE COURSE 

export const GET_ALL_MODULE_OF_MODULE_REQUEST = "GET_ALL_MODULE_OF_COURSEID_REQUEST";
export const GET_ALL_MODULE_OF_COURSEID_SUCCESS = "GET_ALL_MODULE_OF_COURSEID_SUCCESS";
export const GET_ALL_MODULE_OF_COURSEID_FAILURE = "GET_ALL_MODULE_OF_COURSEID_FAILURE";

export const CREATE_MODULE_OF_COURSEID_REQUEST = "CREATE_MODULE_OF_COURSEID_REQUEST";
export const CREATE_MODULE_OF_COURSEID_SUCCESS = "CREATE_MODULE_OF_COURSEID_SUCCESS";
export const CREATE_MODULE_OF_COURSEID_FAILURE = "CREATE_MODULE_OF_COURSEID_FAILURE";

export const GET_MODULE_OF_COURSEID_BY_MODULEID_REQUEST = "GET_MODULE_OF_COURSEID_BY_MODULEID_REQUEST";
export const GET_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS = "GET_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS";
export const GET_MODULE_OF_COURSEID_BY_MODULEID_FAILURE = "GET_MODULE_OF_COURSEID_BY_MODULEID_FAILURE";

export const UPDATE_MODULE_OF_COURSEID_BY_MODULEID_REQUEST = "UPDATE_MODULE_OF_COURSEID_BY_MODULEID_REQUEST";
export const UPDATE_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS = "UPDATE_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS";
export const UPDATE_MODULE_OF_COURSEID_BY_MODULEID_FAILURE = "UPDATE_MODULE_OF_COURSEID_BY_MODULEID_FAILURE";

export const DELETE_MODULE_OF_COURSEID_BY_MODULEID_REQUEST = "DELETE_MODULE_OF_COURSEID_BY_MODULEID_REQUEST";
export const DELETE_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS = "DELETE_MODULE_OF_COURSEID_BY_MODULEID_SUCCESS";
export const DELETE_MODULE_OF_COURSEID_BY_MODULEID_FAILURE = "DELETE_MODULE_OF_COURSEID_BY_MODULEID_FAILURE";

//MODULEITEM 
export const GET_ALL_MODULEITEM_OF_MODULE_REQUEST = "GET_ALL_MODULEITEM_OF_MODULE_REQUEST";
export const GET_ALL_MODULEITEM_OF_MODULE_SUCCESS = "GET_ALL_MODULEITEM_OF_MODULE_SUCCESS";
export const GET_ALL_MODULEITEM_OF_MODULE_FAILURE = "GET_ALL_MODULEITEM_OF_MODULE_FAILURE";

export const CREATE_MODULEITEM_OF_MODULE_REQUEST = "CREATE_MODULEITEM_OF_MODULE_REQUEST";
export const CREATE_MODULEITEM_OF_MODULE_SUCCESS = "CREATE_MODULEITEM_OF_MODULE_SUCCESS";
export const CREATE_MODULEITEM_OF_MODULE_FAILURE = "CREATE_MODULEITEM_OF_MODULE_FAILURE";

export const GET_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST = "GET_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST";
export const GET_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS = "GET_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS";
export const GET_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE = "GET_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE";

export const UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST = "UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST";
export const UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS = "UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS";
export const UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE = "UPDATE_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE";

export const DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST = "DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_REQUEST";
export const DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS = "DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_SUCCESS";
export const DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE = "DELETE_MODULEITEM_OF_MODULE_BY_MODULEID_FAILURE";
